"""add_blueprints_and_import_batches

Revision ID: 69936c2cdac2
Revises: 3a99aac81951
Create Date: 2026-06-13 17:16:05.239216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69936c2cdac2'
down_revision: Union[str, Sequence[str], None] = '3a99aac81951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blueprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('structure', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blueprints_exam_type'), 'blueprints', ['exam_type'], unique=False)
    op.create_index(op.f('ix_blueprints_id'), 'blueprints', ['id'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_report', sa.JSON(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_content_hash'), 'import_batches', ['content_hash'], unique=False)
    op.create_index(op.f('ix_import_batches_id'), 'import_batches', ['id'], unique=False)
    op.add_column('question_groups', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('question_groups', sa.Column('import_batch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_question_groups_content_hash'), 'question_groups', ['content_hash'], unique=False)
    op.create_foreign_key(None, 'question_groups', 'import_batches', ['import_batch_id'], ['id'], ondelete='SET NULL')
    op.add_column('questions', sa.Column('source_question_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('import_batch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_questions_content_hash'), 'questions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_questions_source_question_id'), 'questions', ['source_question_id'], unique=False)
    op.create_foreign_key(None, 'questions', 'questions', ['source_question_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'questions', 'import_batches', ['import_batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_source_question_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_content_hash'), table_name='questions')
    op.drop_column('questions', 'import_batch_id')
    op.drop_column('questions', 'content_hash')
    op.drop_column('questions', 'source_question_id')
    op.drop_constraint(None, 'question_groups', type_='foreignkey')
    op.drop_index(op.f('ix_question_groups_content_hash'), table_name='question_groups')
    op.drop_column('question_groups', 'import_batch_id')
    op.drop_column('question_groups', 'content_hash')
    op.drop_index(op.f('ix_import_batches_id'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_content_hash'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_blueprints_id'), table_name='blueprints')
    op.drop_index(op.f('ix_blueprints_exam_type'), table_name='blueprints')
    op.drop_table('blueprints')
    # ### end Alembic commands ###
